[setup]
nixPkgs = ["php83", "php83Extensions.pdo_pgsql", "php83Extensions.pgsql", "nginx"]

[variables]
NIXPACKS_PHP_EXTENSION_INSTALL = "pdo_pgsql,pgsql"

[start]
cmd = "chmod +x /app/start.sh && /app/start.sh"
